name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@HEAD
    - name: make
      working-directory: 3_Implementation
      run: make all
    - name: make check
      working-directory: 3_Implementation
      run: make check
    - name: make distcheck
      working-directory: 3_Implementation
      run: make distcheck
